Initial commit of the go code.
grubastik/flat-search pull request #1
Opened 2017-03-06 11:57 UTC by grubastik

Next: add tests and add code to use amqp

2017-03-06 12:35 UTC, dkondratovych requested changes

2017-03-06 12:35 UTC, dkondratovych commented on README.md
> +$GOPATH/bin/migrate -url mysql://[DB_USER_NAME]:[DB_USER_PASSWORD]@tcp\([IP_OR_HOSTNAME]:[PORT]\)/[DB_NAME] -path ./migrations/ up
@grubastik to make it cool and flexible, please add make file with all needed commands: 

```
make build
make migrate
make run
make run.docker
make docker.stop
make docker.start
etc 
```

2017-03-06 12:35 UTC, dkondratovych commented on README.md
> +Note2: before using migrations it is required to create DB and grant all necessary permissions to your user.
@grubastik please use `docker compose` to prepare infrastructure

2017-03-06 12:35 UTC, dkondratovych commented on config/parser.go
> +const path = "./config.json"
Config path should be as command line argument and not fixed constant. 
`configPath := flag.String("config", "config.json", "Default config file")`

2017-03-06 12:35 UTC, dkondratovych commented on config/parser.go
> +    error.DebugError(err)
AlWAYS return an error, it's the responsibility of the caller to handle that error. Call method not just `New()`, but `NewConfig()`.

You can use pattern `MustNewConfig()` in that case, it's ok to `panic()` in that method, if further program execution doesn't make sense.

2017-03-06 12:35 UTC, dkondratovych commented on db/storage.go
> +    "./../error"
Use full path, `github.com/grubastik/flat-search/db`. On you local machine code should be located in `~/go/src/github.com/grubastik/flat-search`

2017-03-06 12:35 UTC, dkondratovych commented on db/storage.go
> +func NewStorage(config *config.Config) (*storageEntity) {
Your config has an interface, `GetDb(), GetEmail()...`. Try to return a struct and accept an interface, if possible. Replace `config *config.Config` to something like `config.Config` and make struct `config.Config` private (start struct name from lowercase letter)

2017-03-06 12:35 UTC, dkondratovych commented on email/email.go
> +func (ed *EmailDefinition) setBody(body string) {
Why do you need a method to set a field?

2017-03-06 12:35 UTC, dkondratovych commented on email/smtpDriver.go
> +    if (len(moduleConfig.Username) > 0) {
`if len(moduleConfig.Username) > 0 {`

2017-03-06 12:35 UTC, dkondratovych commented on email/smtpDriver.go
> +func (ed *EmailDefinition) makeSmtpClient() {
Use `context.Context` with any http client

2017-03-06 12:35 UTC, dkondratovych commented on error/error.go
> +func DebugError(err interface{}) {
You can use `panic()` for this. For dev process, you can use better tools like https://github.com/davecgh/go-spew which will give more detailed information about the error

2017-03-06 12:35 UTC, dkondratovych commented on main.go
> +    db.Storage = db.NewStorage(config)
Call it `NewDb()`, basically storages contain business logic, DB stuff and the are intended to be state less

2017-03-06 12:35 UTC, dkondratovych commented on main.go
> +    for _, advert := range *(adverts.GetAdverts()) {
Main should just read console/terminal arguments, read config, connect to db and call some service/storage method to DO business work or start a server/client.. etc. Move this business logic from main somewhere.

2017-03-06 12:35 UTC, dkondratovych commented on models/advert.go
> +func (a *Advert) SetPrice(price float64) {
No need to add those setters methods

2017-03-06 12:35 UTC, dkondratovych commented on models/advert.go
> +        a.Status = "new"
`new` should be a constant

2017-03-06 12:35 UTC, dkondratovych commented on models/advert.go
> +    a.GetLocation().Insert()
Return error here

2017-03-06 12:35 UTC, dkondratovych commented on models/advert.go
> +    db.Storage.Run("UPDATE adverts SET locality = ?, link = ?, hash_id = ?, price = ?, name = ?, status = ? WHERE id = ?",
Return error here

2017-03-06 12:35 UTC, dkondratovych commented on models/advert.go
> +    a.GetLocation().Delete()
Return error here

2017-03-06 12:35 UTC, dkondratovych commented on sreality/request.go
> +    resp, err := http.Get("https://www.sreality.cz/api/cs/v2/estates" + up.GetRequest())
URL should be in config or like a const

2017-03-06 12:35 UTC, dkondratovych commented on README.md
> +```
Use glide for dependency management

2017-03-15 12:12 UTC, dkondratovych requested changes

2017-03-15 12:12 UTC, dkondratovych commented on config/parser.go
> +type Sreality struct{
I would add json notation for all fields

2017-03-15 12:12 UTC, dkondratovych commented on config/parser.go
> +func NewConfig(path *string) (*Config) {
You panic here, so name method `MustNewConfig`

2017-03-15 12:12 UTC, dkondratovych commented on config/parser.go
> +    content, err := ioutil.ReadFile(*path);
Handle error from `ioutil.ReadFile` it doesn't make sense to proceed if there is an error here.

2017-03-15 12:12 UTC, dkondratovych commented on db/storage.go
> +    moduleConfig := config.GetDb();
Use short avriable names for local variables and... why do you need `moduleConfig `variable at all ? 

```go
    if err := storage.Connect(config.GetDb()); err != nil {
         return nil, err
    }
```

2017-03-15 12:12 UTC, dkondratovych commented on db/storage.go
> +    var conn *sql.DB
It's better to declare local err variable, rather than reassign conn.

2017-03-15 12:12 UTC, dkondratovych commented on db/storage.go
> +    result, err := st.db.Exec(sql, options...)
I think the result would be `nil` if `err != nil`, so you can do like `return st.db.Exec(sql, options...)`

2017-03-15 12:12 UTC, dkondratovych commented on db/storage.go
> +func (st *storageEntity) Execute(stmt *sql.Stmt, options... interface{}) (sql.Result, error) {
The same here as in https://github.com/grubastik/flat-search/pull/1/files#r105934103

2017-03-15 12:12 UTC, dkondratovych commented on email/smtpDriver.go
> +type EmailDefinition struct {
It's weird that email definition contains `connection ` -- bad design of responsibilities.

2017-03-15 12:12 UTC, dkondratovych commented on email/smtpDriver.go
> +func (ed *EmailDefinition) Send() (error) {
Change everywhere from `func (ed *EmailDefinition) Send() (error) {` to `func (ed *EmailDefinition) Send() error {`

2017-03-15 12:12 UTC, dkondratovych commented on migrations/1488731199_initial_migration.up.sql
> +CREATE TABLE `adverts` (
Table name should be singular, also add FK

2017-03-15 12:12 UTC, dkondratovych commented on models/advert.go
> +func (a *Advert) GetCreated() time.Time {
Method called `Get...` bit it can set something as well -- not clear. Add method `SetCreatedAt` to set the data.

2017-03-15 12:12 UTC, dkondratovych commented on models/advert.go
> +        return errors.New("Advert does not exist")
Make this error as local variable

```go
var (
     ErrAdvertDoesNotExist = errors.New("Advert does not exist")
)
```

Then you can inspect this error somewhere (and send specific http status code, for example).

2017-03-15 12:12 UTC, dkondratovych commented on sreality/request.go
> +func NewSreality(config *config.Config) (*UrlParams) {
File called `request.go` but you can find a bunch of stuff here. It also good to split client and specific requests to external resources into separate files.

2017-03-15 12:12 UTC, dkondratovych commented on sreality/request.go
> +const configName = "sreality"
I would make `sreality` as a separate package, even in a separate repo. Define clear interface and document what endpoints are implemented and what data they return. So then this package can be reused by someone else and extended.

2017-03-17 19:56 UTC, dkondratovych requested changes
Use https://github.com/alecthomas/gometalinter to verify code for additional errors.

Done

2017-03-17 19:56 UTC, dkondratovych commented on config/parser.go
> +type Email struct{
@grubastik use `go fmt` to format your code

2017-03-17 19:56 UTC, dkondratovych commented on config/parser.go
> +func MustNewConfig(path *string) *Config {
@grubastik why do you need a pointer on `path` variable? When I see `func SomeFunc(var *string)` - I expect that you are going to change `var` inside the function and after the call to `SomeFunc` I will have update value.
Change it to `MustNewConfig(path string) *Config {`

2017-03-17 19:56 UTC, dkondratovych commented on config/parser.go
> +        panic(fmt.Sprintf("%v", err))
` panic(fmt.Sprintf("%v", err))` ==> ` panic(err)`  `func panic(v interface{})` -- Always check function signature.

2017-03-17 19:56 UTC, dkondratovych commented on db/storage.go
> +func (st *storageEntity) Connect(config *config.Db) error {
```
+func (st *storageEntity) Connect(config *config.Db) error {
 +    var err Error
 +    st.db, err = sql.Open(config.Engine, config.Username + ":" + config.Password + "@tcp(" + config.Host + ":" + strconv.Itoa(int(config.Port)) + ")/" + config.Database + "?charset=utf8")
 +    if err != nil {
 +        return nil
 +    }
 +    return nil
 +}
```

====> 

```
func (st *storageEntity) Connect(config *config.Db) error {
     var err error
    st.db, err = sql.Open(config.Engine, config.Username + ":" + config.Password + "@tcp(" + config.Host + ":" strconv.Itoa(int(config.Port)) + ")/" + config.Database + "?charset=utf8")

    return err 
}
```

2017-03-17 19:56 UTC, dkondratovych commented on email/email.go
> +    from *mail.Address
Why do you need a pointer here? I think `mail.Address` is enough.

2017-03-17 19:56 UTC, dkondratovych commented on main.go
> +    error.DebugError(err)
Change this to `log.Fatal()`

2017-03-17 19:56 UTC, dkondratovych commented on models/location.go
> +    _, err := db.Storage.Run("DELETE FROM location WHERE id = ?", l.Id)
```go
+    _, err := db.Storage.Run("DELETE FROM location WHERE id = ?", l.Id)
 +    if err != nil {
 +        return err
 +    }
 +    return nil
```

==> 
```go
+    _, err := db.Storage.Run("DELETE FROM location WHERE id = ?", l.Id)

 +    return err
```

2017-03-17 19:56 UTC, dkondratovych commented on sreality/request.go
> +    if len(*up.category_sub_cb) > 0 {
If field can be a `nil`, it's good practice to check if `!= nil` first. 

```go
if  up.category_sub_cb !=nil && len(*up.category_sub_cb) > 0 {
```

You would get an error `invalid memory address or nil pointer dereference` if field is nil and you are trying to pointer value.

2017-03-17 19:56 UTC, dkondratovych commented on sreality/request.go
> +func getStringFromIntSlice(val *[]int) string {
`val *[]int` ==> `val []int`

2017-03-17 19:56 UTC, dkondratovych commented on sreality/response.go
> +    Estates *[]advert `json:"estates"`
Why not `[]advert` ?

2017-03-17 19:56 UTC, dkondratovych commented on sreality/response.go
> +    Category_main_cb int64 `json:"category_main_cb"`
`Category_main_cb` -- ONLY camel case. Please change in all structs.

2017-03-17 20:51 UTC, dkondratovych requested changes

2017-03-17 20:51 UTC, dkondratovych commented on email/smtpDriver.go
> +    ec.makeSmtpClient()
It's kind of overhead create client on each `Send` action. Init your client/open connection and keep that client in memory. What if you need to send 100000 emails? With current logic, you need to connect to smtp server upon sending each email.

2017-03-17 21:28 UTC, dkondratovych commented on email/smtpDriver.go
> +    // To && From
Add logging for each request, with detailed request/response information. This will help track issues during creating email envelope/content.

2017-03-18 14:06 UTC, grubastik commented on config/parser.go
> +type Sreality struct{
done

2017-03-18 14:06 UTC, grubastik commented on config/parser.go
> +func NewConfig(path *string) (*Config) {
done

2017-03-18 14:06 UTC, grubastik commented on config/parser.go
> +    content, err := ioutil.ReadFile(*path);
done

2017-03-18 14:07 UTC, grubastik commented on db/storage.go
> +    moduleConfig := config.GetDb();
done

2017-03-18 14:07 UTC, grubastik commented on db/storage.go
> +    var conn *sql.DB
done

2017-03-18 14:07 UTC, grubastik commented on db/storage.go
> +    result, err := st.db.Exec(sql, options...)
done

2017-03-18 14:08 UTC, grubastik commented on db/storage.go
> +func (st *storageEntity) Execute(stmt *sql.Stmt, options... interface{}) (sql.Result, error) {
done

2017-03-18 14:08 UTC, grubastik commented on email/smtpDriver.go
> +type EmailDefinition struct {
done

2017-03-18 14:08 UTC, grubastik commented on email/smtpDriver.go
> +func (ed *EmailDefinition) Send() (error) {
done

2017-03-18 14:08 UTC, grubastik commented on migrations/1488731199_initial_migration.up.sql
> +CREATE TABLE `adverts` (
done

2017-03-18 14:09 UTC, grubastik commented on models/advert.go
> +func (a *Advert) GetCreated() time.Time {
done

2017-03-18 14:09 UTC, grubastik commented on models/advert.go
> +        return errors.New("Advert does not exist")
done

2017-03-18 20:07 UTC, dkondratovych commented on models/advert.go
> +    Id int64
Change `Id` to `ID`

2017-03-18 20:08 UTC, dkondratovych commented on models/advert.go
> +    HashId int64
Rename `HashId` to `HashID`.

2017-03-19 13:27 UTC, dkondratovych commented on README.md
> +```
Add `$GOPATH` to your `PATH` so you can just run `migrate`.

2017-03-19 13:28 UTC, dkondratovych commented on README.md
> +```
You can use https://github.com/seesawlabs/mighero That package will allow you to read `DB_USER_NAME ` and other parameters from your config file.

2017-03-19 13:51 UTC, dkondratovych commented
@grubastik read code review guide and update your code accordingly 
https://github.com/golang/go/wiki/CodeReviewComments

2017-03-19 13:59 UTC, dkondratovych commented on sreality/request.go
> +    if len(*up.category_sub_cb) > 0 {
**__2__**
Read

Read https://blog.golang.org/go-slices-usage-and-internals
http://stackoverflow.com/questions/33995634/are-golang-function-parameter-passed-as-copy-on-write
http://stackoverflow.com/questions/39993688/are-golang-slices-pass-by-value

2017-03-21 08:59 UTC, grubastik commented on sreality/response.go
> +    Category_main_cb int64 `json:"category_main_cb"`
done

2017-03-21 09:01 UTC, grubastik commented on db/storage.go
> +func (st *storageEntity) Connect(config *config.Db) error {
done

2017-03-21 09:02 UTC, grubastik commented on config/parser.go
> +type Email struct{
done

2017-03-21 09:05 UTC, grubastik commented on models/advert.go
> +    Id int64
done

2017-03-21 09:05 UTC, grubastik commented on models/advert.go
> +    HashId int64
done

2017-03-21 09:06 UTC, grubastik commented on models/location.go
> +    _, err := db.Storage.Run("DELETE FROM location WHERE id = ?", l.Id)
Removed method. Use Run instead.

2017-03-21 10:57 UTC, dkondratovych commented on config/parser.go
> +type Email struct{
@grubastik did you push your last changes ?
```go
// current formatting
+type Db struct {
 +    Engine string `json:"engine"`
 +    Host string `json:"host"`
 +    Port int `json:"port"`
 +    Username string `json:"username"`
 +    Password string `json:"password"`
 +    Database string `json:"database"`
 +}
```

```go
// It should look like
type Db struct {
	Engine   string `json:"engine"`
	Host     string `json:"host"`
	Port     int    `json:"port"`
	Username string `json:"username"`
	Password string `json:"password"`
	Database string `json:"database"`
}
```

2017-03-24 09:37 UTC, grubastik commented on README.md
> +$GOPATH/bin/migrate -url mysql://[DB_USER_NAME]:[DB_USER_PASSWORD]@tcp\([IP_OR_HOSTNAME]:[PORT]\)/[DB_NAME] -path ./migrations/ up
done

2017-03-27 07:42 UTC, grubastik commented on README.md
> +Note2: before using migrations it is required to create DB and grant all necessary permissions to your user.
done

2017-03-27 16:46 UTC, dkondratovych commented on Makefile
> +check:
👍

2017-03-27 17:44 UTC, dkondratovych requested changes

2017-03-27 17:44 UTC, dkondratovych commented on config/parser.go
> +func MustNewConfig(path *string) *Config {
`MustNewConfig(path *string)` ==> `MustNewConfig(path string)`

2017-03-27 17:44 UTC, dkondratovych commented on config/parser.go
> +		panic(fmt.Sprintf("%v", err))
`panic(fmt.Sprintf("%v", err))` => `panic(err)`

2017-03-27 17:44 UTC, dkondratovych commented on config/parser.go
> +	if os.Getenv("DB_HOST") != "" {
```go
+	if os.Getenv("DB_HOST") != "" {
 +		config.Db.Host = os.Getenv("DB_HOST")
 +	}
```

==> 
```go

+	if dbHost := os.Getenv("DB_HOST"); dbHost != "" {
 +		config.Db.Host = dbHost
 +	}
```

2017-03-27 17:44 UTC, dkondratovych commented on email/smtpDriver.go
> +	Conn = new(Connection)
You can rename `Conn ` => `c `

2017-06-12 11:19 UTC, dkondratovych commented on config/parser.go
> +type Sreality struct {
If you want to have sreality as a separate package (and used by someone elsse), keep this config in that sreality package.

2017-06-12 11:21 UTC, dkondratovych commented on sreality/detail.go
> +type key string
`go fmt` this file

2017-06-12 11:23 UTC, dkondratovych commented on sreality/detail.go
> +    var d = new(Detail)
I would avoid using `new`. 
```
d := Detail{}

err = json.Unmarshal(body, &d)

return &d, nil
```

2017-06-12 11:24 UTC, dkondratovych commented on sreality/list.go
> +    request := ""
`request := ""` => `var request string`

2017-10-28 15:37 UTC, merged